py_module:
    - empty:
        - info: Empty module
        - template: empty.template
    - main:
        - info: Main module
        - template: main.template
    - class:
        - info: Class module
        - template: class.template
    - abstract_base:
        - info: Abstract base module
        - template: abstract_base_class.template
    - abstract_abc:
        - info: Abstract ABC base module
        - template: abstract_abc_class.template
    - cancel:
        - info: null
        - template: null
